lea_resp_homepage:
    path:     /resp
    defaults: { _controller: LEARespBundle:Default:index }

lea_resp_attribution:
    path:    /resp/attribution
    defaults: { _controller: LEARespBundle:Attribution:index }

lea_resp_affecter:
    path:    /resp/affecter
    defaults: { _controller: LEARespBundle:Affecter:index }

lea_resp_changeForm:
    path:    /resp/ajax/changeForm
    defaults: { _controller: LEARespBundle:Attribution:changeForm }
    requirements:
        _method: POST
    options:
        expose: true

lea_resp_rapportSoutenance:
    path:    /resp/soutenance
    defaults: { _controller: LEARespBundle:Soutenance:index }

lea_resp_editRapportSout:
    path:    /resp/soutenance/{forma}
    defaults: { _controller: LEARespBundle:Soutenance:edit }

lea_resp_stats_index:
    path:    /resp/stats
    defaults: { _controller: LEARespBundle:Stats:index }

lea_resp_stats_form:
    path:    /resp/stats/form
    defaults: { _controller: LEARespBundle:StatsForm:index }

lea_resp_stats_tuteurs:
    path:    /resp/stats/tuteurs
    defaults: { _controller: LEARespBundle:StatsTuteurs:index }

lea_resp_stats_besoins:
    path:    /resp/stats/besoins
    defaults: { _controller: LEARespBundle:StatsBesoins:index }

lea_resp_stats_entreprise:
    path:    /resp/stats/entreprise
    defaults: { _controller: LEARespBundle:StatsEntreprise:index }

lea_resp_stats_opca:
    path:    /resp/stats/opca
    defaults: { _controller: LEARespBundle:StatsOpca:index }
