lea_resp_homepage:
    path:     /resp
    defaults: { _controller: LEARespBundle:Default:index }

lea_resp_attribution:
    path:    /resp/attribution
    defaults: { _controller: LEARespBundle:Attribution:index }

lea_resp_affecter:
    path:    /resp/affecter
    defaults: { _controller: LEARespBundle:Affecter:index }

lea_resp_changeForm:
    path:    /resp/ajax/changeForm
    defaults: { _controller: LEARespBundle:Attribution:changeForm }
    requirements:
        _method: POST
    options:
        expose: true

lea_resp_rapportSoutenance:
    path:    /resp/soutenance
    defaults: { _controller: LEARespBundle:Soutenance:index }

lea_resp_editRapportSout:
    path:    /resp/soutenance/{forma}
    defaults: { _controller: LEARespBundle:Soutenance:edit }