lea_resp_homepage:
    path:     /resp
    defaults: { _controller: LEARespBundle:Default:index }


lea_resp_attribution:
    path:    /resp/attribution
    defaults: { _controller: LEARespBundle:Attribution:index }