imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'LEAEtuBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: "stalt"
        connections:
            departement:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "fil_dept"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            entreprises:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "fil_entr"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            stalt:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "stalt"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            candidatures:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "candidatures"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: "stalt"
        entity_managers:
            departement:
                connection: "departement"
                mappings:
                    LEAEtuBundle: ~
                    LEAProfBundle: ~
                    LEARespBundle: ~
            entreprises:
                connection: "entreprises"
                mappings:
                    LEAEtuBundle: ~
                    LEAProfBundle: ~
                    LEARespBundle: ~
            stalt:
                connection: "stalt"
                mappings:
                    LEAEtuBundle: ~
                    LEAProfBundle: ~
                    LEARespBundle: ~
            candidatures:
                connection: "candidatures"
                mappings:
                    LEAEtuBundle: ~
                    LEAProfBundle: ~
                    LEARespBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


services:
    queries:
        class: LEA\Services\Dbmngt\Queries
    dbutils:
        class: LEA\Services\Dbmngt\DbUtils
    queries_etapes:
        class: LEA\Services\Dbmngt\queriesEtapes
    queries_sout:
        class: LEA\Services\Dbmngt\QueriesSout
    queriesEtu:
        class: LEA\Services\Dbmngt\queriesEtu
    update_queries:
        class: LEA\Services\Dbmngt\UpdateQueries
    inscrire:
        class: LEA\Services\Dbmngt\Inscrire
    normaliser:
        class: LEA\Services\Dbmngt\Normaliser
    distance:
        class: LEA\Services\Distance\CalculDistance
    html_utils:
        class: LEA\Services\Html\Utils
