lea_etu_homepage:
    path:     /etudiant/{name}
    defaults: { _controller: LEAEtuBundle:Default:index }

lea_etu_infosStage:
    path:    /etudiant/{name}/infosStage
    defaults: { _controller: LEAEtuBundle:Stage:index }

lea_etu_afficherInfosStage:
    path:    /etudiant/{name}/infosStage/afficher
    defaults: { _controller: LEAEtuBundle:Stage:afficherInfos }

lea_etu_inscrireEntr:
    path:    /etudiant/{name}/infosStage/inscrireEntr
    defaults: { _controller: LEAEtuBundle:Stage:inscrireEntr }

lea_etu_inscrireBureau:
    path:    /etudiant/{name}/infosStage/{entr}/inscrireBureau
    defaults: { _controller: LEAEtuBundle:Stage:inscrireBureau }
    options:
        expose: true

lea_etu_inscrireRef:
    path:    /etudiant/{name}/infosStage/{entr}/inscrireRef
    defaults: { _controller: LEAEtuBundle:Stage:inscrireRef }
    options:
         expose: true

lea_etu_appel_ajax_entr:
    path:    /etudiant/infosStage/creerListe
    defaults: { _controller: LEAEtuBundle:Stage:ajaxEntr }
    requirements:
        _method: POST
    options:
        expose: true

lea_etu_appel_ajax_regie:
    path:    /etudiant/infosStage/creerListe
    defaults: { _controller: LEAEtuBundle:Stage:ajaxRegie }
    requirements:
        _method: POST
    options:
        expose: true

lea_etu_infosMission:
    path:    /etudiant/{name}/infosMission
    defaults: { _controller: LEAEtuBundle:Mission:index }

lea_etu_soutenanceRapport:
    path:    /etudiant/{name}/soutenanceRapport
    defaults: { _controller: LEAEtuBundle:SoutenanceRapport:index }

lea_etu_rencontreTuteur:
    path:    /etudiant/{name}/rencontreTuteur
    defaults: { _controller: LEAEtuBundle:Rencontre:index }

lea_etu_rencontreTuteurRendu:
    path:    /etudiant/{name}/rencontreTuteurRendu
    defaults: { _controller: LEAEtuBundle:Rencontre:Rendu }

lea_etu_visiteUn:
    path:    /etudiant/{name}/visiteUn
    defaults: { _controller: LEAEtuBundle:VisiteUn:index }

lea_etu_visiteUnRendu:
    path:    /etudiant/{name}/visiteUnRendu
    defaults: { _controller: LEAEtuBundle:VisiteUn:rendu }

lea_etu_visiteDeux:
    path:    /etudiant/{name}/visiteDeux
    defaults: { _controller: LEAEtuBundle:VisiteDeux:index }

lea_etu_visiteDeuxRendu:
    path:    /etudiant/{name}/visiteDeuxRendu
    defaults: { _controller: LEAEtuBundle:VisiteDeux:rendu }

lea_etu_missionSoutenance:
    path:    /etudiant/{name}/missionSoutenance
    defaults: { _controller: LEAEtuBundle:MissionSoutenance:index }

lea_etu_missionSoutenanceRendu:
    path:    /etudiant/{name}/missionSoutenanceRendu
    defaults: { _controller: LEAEtuBundle:MissionSoutenance:rendu }