lea_etu_homepage:
    path:     /etudiant/{name}
    defaults: { _controller: LEAEtuBundle:Default:index }

lea_etu_infosMission:
    path:    /etudiant/{name}/infosMission
    defaults: { _controller: LEAEtuBundle:Mission:index }

