lea_prof_homepage:
    path:     /prof/{name}
    defaults: { _controller: LEAProfBundle:Default:index }

lea_prof_choisir:
    path:    /prof/{name}/choisir
    defaults: { _controller: LEAProfBundle:Choisir:index}

lea_prof_etuAttribues:
    path:    /prof/{name}/etuAttribues
    defaults: { _controller: LEAProfBundle:EtuAttribues:index}

lea_prof_etuGeneral:
    path:    /prof/{name}/etuAttribues/{nameEtu}/general
    defaults: { _controller: LEAProfBundle:General:index}
    options:
            expose: true

lea_prof_modifierEtuGeneral:
    path:    /prof/{name}/etuAttribues/{nameEtu}/general/modifer
    defaults: { _controller: LEAProfBundle:General:index}
    options:
            expose: true

lea_prof_changeForm:
    path:    /prof/ajax/changeForm
    defaults: { _controller: LEAProfBundle:Choisir:changeForm }
    requirements:
        _method: POST
    options:
        expose: true

lea_prof_changeAction:
    path:    /prof/ajax/changeAction
    defaults: { _controller: LEAProfBundle:EtuAttribues:changeActionProf }
    requirements:
        _method: POST
    options:
        expose: true

lea_prof_suivi:
    path:    /prof/{name}/suivi
    defaults: { _controller: LEAProfBundle:Suivi:index}

lea_prof_suiviSuppr:
    path:    /prof/ajax/suiviSuppr
    defaults: { _controller: LEAProfBundle:Suivi:suppr }
    requirements:
        _method: POST
    options:
        expose: true