lea_prof_homepage:
    path:     /prof
    defaults: { _controller: LEAProfBundle:Default:index }

lea_prof_choisir:
    path:    /prof/choisir
    defaults: { _controller: LEAProfBundle:Choisir:index}

lea_prof_rapportSoutenance:
    path:    /prof/rapportsoutenance
    defaults: { _controller: LEAProfBundle:RapportSoutenance:index}

lea_prof_etuAttribues:
    path:    /prof/etuAttribues
    defaults: { _controller: LEAProfBundle:EtuAttribues:index}

lea_prof_etuGeneral:
    path:    /prof/etuAttribues/{name}/general
    defaults: { _controller: LEAProfBundle:General:index}
    options:
            expose: true

lea_prof_etuRencontre:
    path:    /prof/etuAttribues/{name}/rencontre
    defaults: { _controller: LEAProfBundle:EtuAttriRencontre:index}
    options:
        expose: true

lea_prof_etuRencontreEdit:
    path:    /prof/etuAttribues/{name}/rencontreEdit
    defaults: { _controller: LEAProfBundle:EtuAttriRencontre:rendu}
    options:
        expose: true

lea_prof_etuVisiteUn:
    path:    /prof/etuAttribues/{name}/visiteUn
    defaults: { _controller: LEAProfBundle:EtuAttriVisiteUn:index}
    options:
        expose: true

lea_prof_etuVisiteUnEdit:
    path:    /prof/etuAttribues/{name}/visiteUnEdit
    defaults: { _controller: LEAProfBundle:EtuAttriVisiteUn:rendu}
    options:
        expose: true

lea_prof_etuVisiteDeux:
    path:    /prof/etuAttribues/{name}/visiteDeux
    defaults: { _controller: LEAProfBundle:EtuAttriVisiteDeux:index}
    options:
        expose: true

lea_prof_etuVisiteDeuxEdit:
    path:    /prof/etuAttribues/{name}/visiteDeuxEdit
    defaults: { _controller: LEAProfBundle:EtuAttriVisiteDeux:rendu}
    options:
        expose: true

lea_prof_modifierEtuGeneral:
    path:    /prof/etuAttribues/{name}/general/modifer
    defaults: { _controller: LEAEtuBundle:Stage:index}
    options:
            expose: true

lea_prof_odm:
    path:    /prof/etuAttribues/{name}/odm
    defaults: { _controller: LEAProfBundle:ODM:index}
    options:
            expose: true

lea_prof_creerOdm:
    path:    /prof/etuAttribues/{name}/odm/generer
    defaults: { _controller: LEAProfBundle:ODM:creer}
    options:
            expose: true


lea_prof_changeForm:
    path:    /prof/ajax/changeForm
    defaults: { _controller: LEAProfBundle:Choisir:changeForm }
    requirements:
        _method: POST
    options:
        expose: true

lea_prof_changeAction:
    path:    /prof/ajax/changeAction
    defaults: { _controller: LEAProfBundle:EtuAttribues:changeActionProf }
    requirements:
        _method: POST
    options:
        expose: true

lea_prof_suivi:
    path:    /prof/{name}/suivi
    defaults: { _controller: LEAProfBundle:Suivi:index}
    options:
       expose: true

lea_prof_suiviSuppr:
    path:    /prof/ajax/suiviSuppr
    defaults: { _controller: LEAProfBundle:Suivi:suppr }
    requirements:
        _method: POST
    options:
        expose: true