EtudiantGroupe:
    type: entity
    table: etudiant_groupe
    id:
        annee:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            id: true
        etudref:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            id: true
            column: etudRef
    fields:
        grouperef:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: groupeRef
    lifecycleCallbacks: {  }
